### ISSUE TITLE
Using `jupyterbook-latex`

### ISSUE THREAD

**Issue by amichuda** [executablebooks/jupyterbook-latex#2]
Currently, once I've installed `jupyterbook-latex`, do I then add it as an extra extension in the `_config.yml` file to be able to use?

**Comment by AakashGfude** [comment]
that's right @amichuda , hopefully you be able to use it . Add `jupyterbook_latex` as an extra extension.

**Comment by amichuda** [comment]
Great, thank you! One more question. Is there a way to set a global option for all code cells? So that, for instance, all cells have the `remove-input` tag by default.

**Comment by AakashGfude** [comment]
@amichuda not at present. Maybe we can deliberate on it, and implement it if it is useful enough.

cc: @choldgraf @mmcky @chrisjsewell

**Comment by amichuda** [comment]
Huzzah! It works on my end. Will report back with issues.

But it would be nice, especially in an academic context if there was no input code shown in a PDF by default, unless specified.

**Comment by AakashGfude** [comment]
@amichuda hmm. Ideally, I think this should be a part of a theme or "mode/flag". For example, there can be a theme for academic writing, which comes with this default and other things that will totally make sense there.  And then there can be a theme for lectures, tutorials and stuff etc.
As far as the current default goes for this theme, based on the user requirements can be suggested more concretely by @choldgraf I think.

**Comment by choldgraf** [comment]
hmmm - I don't have a good understanding of the Latex needs of users for Jupyter Book - I haven't used Latex much so don't have an intuition for what it needs to do, will leave that thinking up to @mmcky and @AakashGfude :-)

But in general I think a good first step is to document how people can activate this in Jupyter Book via the docs, as well as information about what the package does etc, and then once the code has stabilized a bit, and we've seen how people use it, then we can talk about how to integrate it as a default

**Comment by mmcky** [comment]
I think what @amichuda is asking for is the option to apply a global override via `_config.yml` to remove all `code` blocks and apply [hide-input](https://jupyterbook.org/interactive/hiding.html#hide-cell-inputs) or `remove-input` tags such as something like:

```yaml
code-cell:
  tag: hide-input
```

which would add that tag to **all** code-cells. Is that right @amichuda?

I think the tricky part here is someone will inevitably want to `hide` all and then show `some` again. I think cell-level tags isn't overly onerous to add and the right level for these settings.

**Comment by choldgraf** [comment]
ah gotcha - that sounds like a separate issue to me, so perhaps better to discuss elsewhere (so it isn't embedded in an issue about latex)

The challenge with this, as you describe, is that we'd need to add a new CSS class. That's probably not a huge deal if enough folks want it, but it would double the number of CSS classes we gotta keep track of (for hiding, for removing, for scrolling, etc)

**Comment by mmcky** [comment]
Done: https://github.com/executablebooks/jupyter-book/issues/1093
