### ISSUE TITLE
JupyterBook Class overrides manual config changes in _config.yml

### ISSUE THREAD

**Issue by amichuda** [executablebooks/jupyterbook-latex#25]
When using the `jupyterbook-latex` extension and then making an override to `latex_docclass` or `latex_elements`, `jupyterbook` still compiles with the `jupyterbook_latex` .cls file, which includes fontsize information as well. Here's the relevant part of my `_config.yml`

```
sphinx:
  extra_extensions:
    - jupyterbook_latex
  config: 
    latex_elements: 
      pointsize: 12pt
    latex_docclass:
      manual : article
```

**Comment by amichuda** [comment]
From what I see now, it also depends on whether you put the extra extension before or after `config`. Is that intended behavior?

**Comment by AakashGfude** [comment]
Hey @amichuda, thanks for testing out this case. This is not intended behavior and I agree that the values specified manually should override the .cls file. Will have a look at it.
