### ISSUE TITLE
use `pandoc` to convert to latex PDF

### ISSUE THREAD

**Issue by amichuda** [executablebooks/jupyterbook-latex#29]
Don't know if this as been discussed or if it's feasible/a good idea.

Right now, as it stands (with my limited knowledge of sphinx), the latex to PDF conversion has a very specific use case with a particular document class and breaking away from that use case (like, let's say writing an academic paper) requires a lot of `conf.py` changes. For instance, I'm not sure of an easy way to just use the regular old `latex article documentclass` without it being somehow turned into a `sphinx` manual somwhere along the way. I've been trying to figure out a way for `sphinx` to allow me to put in a regular `latex article` abstract, but once sphinx does its thing, and then the `jupyterBook.cls` is applied, it's not clear what's being overriden and where things need to be changed or which latex option the `_config.yml` even reads, but that might just be my lack of understanding.

On the other hand, `pandoc` has the perfect feature set already with a very developed way of converting `markdown -> latex -> PDF`. If we add `jupytext` to that, `MyST MD` can be converted to `pandoc markdown`. 

So my suggestion/question is: how difficult would it be to let `pandoc` be the backend that converts notebook into `latex` PDFs? It seems like with `sphinx` there would have to be a lot of finagling needed in order to get rid of all "sphinxy` things if you need more of an academically styled paper, and you wouldn't need to reinvent a lot of the wheel. The way I see it working is this:

```
Jupyter file/markdown file -> MyST-NB -> MyST MD file with outputs -> Pandoc MD through jupytext -> Latex -> PDF
```

If that is not feasible, would it be possible to output a MyST MD markdown notebook to be output so that we can do the conversion ourselves?

**Comment by choldgraf** [comment]
Hmmm - I suspect that this would be a really significant amount of work and a full departure from how we're currently building Latex files via Sphinx. A big challenge of not going through Sphinx is that all of the roles/directives/etc supported in Jupyter Book would not work until they were hand-coded in there as well (since Sphinx handles all of these).

It would be very cool to see people prototyping and playing around with how to go from MyST notebooks into Latex via Pandoc, but to me this sounds like a separate project from Jupyter Book directly :-/

**Comment by amichuda** [comment]
Yeah that makes sense. In that case, is there a way to export a Myst-NB notebook as markdown with outputs written that can be used by jupytext to turned into pandoc markdown?

**Comment by choldgraf** [comment]
hmmm, I believe that @mmcky mentioned the quantecon team have a way to generate Jupyter Notebooks that are commonmark-compliant using Sphinx. That could be paired with Pandoc (which knows how to read `ipynb`) to convert them into Latex. I'd be curious to hear about your experiences if you play around with this!

**Comment by mmcky** [comment]
This is an interesting proposal. 

We are working on [jupyterbook-latex](https://github.com/executablebooks/jupyterbook-latex) to support improvements to the LaTeX and PDF build chain and @AakashGfude is working to make this available more easily for `jupyter-book`

There is also a project [sphinx-tojupyter](https://github.com/quantecon/sphinx-tojupyter) in `alpha` phase of development that @choldgraf is referring to. We are currently working our way through the various `docutils` and `sphinx` nodes to figure out which ones need further support and intend to use this to build `download notebooks` in the short/medium term as we work through the best `technical` pathway to alter `jupyter notebooks` from the source `myst` notebooks`. It is essentially an extension that builds `jupyter notebooks` from `sphinx` abstract syntax tree. 

However, my only word of caution from having built [sphinxcontrib-jupyter](https://github.com/quantecon/sphinxcontrib-jupyter) to power the `quantecon` lecture projects is that chains of conversion are really difficult to work with. In that project we built via `nbconvert` and made `notebooks` a primary format via `sphinx` so we could build notebooks of various states. However the `rst` -> `sphinx` -> `ipynb` -> `html` (via `nbconvert` and HTML templates) was onerous and moving to `source` -> `sphinx` -> `html` was a primary goal when moving to `jupyter-book`

**Comment by amichuda** [comment]
I think this issue is neither here nor there in terms of jupyterbook solving this problem so I'm going to close it. Thanks!
