### ISSUE TITLE
Remove the dependency on Jupyter Book or sphinx-external-toc

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/jupyterbook-latex#59]
We've just released a new version of `sphinx-external-toc` and realized that we have a circular dependency between `jupyterbook-latex`, `jupyter-book`, and `sphinx-external-toc`.

From the PR where we discovered this, @chrisjsewell noted:

> Really jupyterbook-latex no longer needs to depend on jupyter-book for testing (now that it uses this package for toc based stuff and is "independent" of jupyter-book), so those tests can be removed to remove the circular dependency

So I think we have two options:

- remove tests in this repository that *depend* on Jupyter Book, remove the dependency on jupyter book, and pin only to a specific version of `sphinx-external-toc`
- remove the dependency on `sphinx-external-toc` and inherit it from `jupyter-book`

I think we need to resolve this (or at least release a new version of this repo) before we can release a new version of Jupyter Book so that we don't create a version conflict.

**Comment by mmcky** [comment]
@choldgraf the way we have been thinking of this repo is as an extension to `jupyter-book` so I think option 2 makes sense. @chrisjsewell has suggested we turn this into a pure `sphinx` extension so we could at that stage look at dropping dependency on `jupyter-book` and `sphinx-external-toc`

cc: @AakashGfude

**Comment by chrisjsewell** [comment]
> the way we have been thinking of this repo is as an extension to jupyter-book so I think option 2 makes sense. @chrisjsewell has suggested we turn this into a pure sphinx extension so we could at that stage look at dropping dependency on jupyter-book and sphinx-external-toc

What, no option 1 is the **only** option. I've already turned it into a pure sphinx extension, that was the whole point of my refactor 😬, there is already no dependency on jupyter-book, just some legacy testing. There is also no direct dependency on sphinx-external-toc

**Comment by AakashGfude** [comment]
But, `jupyterbook-latex` does use some config variables declared in `jupyter-book` like `jblatex_captions_to_parts` ? 
But also, currently when implementing `tableofcontents` directive for latex, I am using the `site_map` provided by `sphinx-external-toc`. So, it kinda depends on both 👀 ?

**Comment by chrisjsewell** [comment]
You can see this already in the `install_requires`, the only requirement is sphinx. 

In fact really you can just relax the version pinning of sphinx-external-toc (to include v0.2.0) in the test extra and that should be fine

**Comment by mmcky** [comment]
@chrisjsewell just digging into this and looking at the `setup.cfg`. 

Was thinking of updating 

```
sphinx-external-toc~=0.1.0
```

to be 

```
sphinx-external-toc>=0.1.0
```

> I've already turned it into a pure sphinx extension

Right -- so we should probably also rename this repo something like `sphinx-jupyterbook-latex`. 

> jupyterbook-latex does use some config variables declared in jupyter-book like jblatex_captions_to_parts

@AakashGfude just looking at `events.py` and it seems those config values are being pulled from `sphinx.app` now.

**Comment by chrisjsewell** [comment]
> But, jupyterbook-latex does use some config variables declared in jupyter-book like jblatex_captions_to_parts?

No it doesn't, that's a variable of this extension, it's not in any way dependant on jupyter-book.

**Comment by chrisjsewell** [comment]
> sphinx-external-toc>=0.1.0

Always include a top pinning, so sphinx-external-toc>=0.1.0,<0.3.0

**Comment by chrisjsewell** [comment]
> Right -- so we should probably also rename this repo something like sphinx-jupyterbook-latex.

Yep that's a possibility 👍

**Comment by mmcky** [comment]
> > Right -- so we should probably also rename this repo something like sphinx-jupyterbook-latex.
> 
> Yep that's a possibility 👍

I have opened #61 to discuss the options

**Comment by choldgraf** [comment]
So I’m a bit confused because https://github.com/executablebooks/jupyterbook-latex/pull/60 didn’t seem to remove the Jupyter-book dependency. Can somebody confirm that this issue is no longer an issue? Or post what needs to be done to close this issue?

**Comment by mmcky** [comment]
@choldgraf the [setup.cfg](https://github.com/executablebooks/jupyterbook-latex/blob/master/setup.cfg) only lists jupyter-book in `testing` dependencies. So it shouldn't depend on `jupyter-book` via standard install. Where do you see the dependency issue?

**Comment by mmcky** [comment]
@choldgraf does this make sense? Is there anything else I can help with here?

I think the change suggested by @chrisjsewell resolves a version pinning conflict (causing the circular dependency issue?)

**Comment by mmcky** [comment]
I have setup a release https://github.com/executablebooks/jupyterbook-latex/pull/63 once approved by @chrisjsewell I can merge and push to `PyPI`

**Comment by mmcky** [comment]
@choldgraf I went ahead and merged #63 so should be available for the `jupyter-book=0.11` release
