### ISSUE TITLE
Rename extension sphinx-jupyterbook-latex

### ISSUE THREAD

**Issue by mmcky** [executablebooks/jupyterbook-latex#61]
**Is your feature request related to a problem? Please describe.**

This is now a `sphinx` extension based on #55 so we should rename this to be `sphinx-`

Candidates include:

1. `sphinx-jupyterbook-latex`
2. `sphinx-jb-latex`

I think the first option is pretty good. 
While it links this extension to `jupyterbook` (which is essentially not needed) but I think `sphinx-latex` is too generic.

Opening this issue for discussion before making the change

cc: @chrisjsewell @choldgraf @AakashGfude

**Comment by AakashGfude** [comment]
I think, even though it does not depend on `jupyter-book` , it caters to `jupyter-book`.  So, the candidates look legit to me. 
Preference wise 1) . As it is easier to search when someone looks for extensions of `jupyter-book` ?

**Comment by choldgraf** [comment]
+1 to option 1 as well

**Comment by mmcky** [comment]
As part of the next release we will need to:

- [ ] rename actual `github repo`
- [ ] Setup via PyPI
- [ ] Setup via Conda Forge
- [x] Update `jupyter-book` with new version pinning and updated package name (https://github.com/executablebooks/jupyter-book/pull/1340)
