### ISSUE TITLE
[review] table of contents Part 1 consists of Section 1 from all Parts

### ISSUE THREAD

**Issue by mmcky** [executablebooks/jupyterbook-latex#9]
**Describe the bug**

For lecture-python-programming project

The first `part` seems to consist of the first section from every Part (i.e. 2,3,4) and then starts again with `part1` as `part2`. 

<img width="681" alt="Screen Shot 2020-12-10 at 8 51 27 pm" src="https://user-images.githubusercontent.com/8263752/101756009-ab62aa00-3b29-11eb-94d9-f9026da1357f.png">

Perhaps there is an issue with the parsing of the `toctree`?

**Comment by AakashGfude** [comment]
fixed in version `0.1.4`
